[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "opencap_overlay"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "opencv-python",
    "pillow",
    "pyrender",
    "pyvista",
    "tqdm",
    "trimesh",
]

[tool.hatch.build.targets.wheel]
packages = ["opencap_overlay"]
